version:  '3.1'
services:
  app:
    container_name: blogger
    image: blogger
    build: ./
    ports:
      -  "9091:9090"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=market6033
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=postgres